(function(){
'use strict';
const RK=window.RKCatalog;if(!RK)return;
function add(target,rows){const seen=new Set(target.map(x=>x.slug));rows.forEach(r=>{if(seen.has(r[0]))return;seen.add(r[0]);target.push({slug:r[0],name:r[1],tags:r[2]});});}
function addServices(rows){const seen=new Set(RK.services.map(x=>x.slug));rows.forEach(r=>{if(seen.has(r[0]))return;seen.add(r[0]);RK.services.push({slug:r[0],name:r[1],mode:r[2],tags:r[3]});});}
add(RK.niches,[
['ophthalmology-clinic','Офтальмологическая клиника',['medical','local']],['diagnostic-center','Диагностический центр',['medical','local']],['mri-center','МРТ и КТ центр',['medical','local']],['rehab-center','Реабилитационный центр',['medical','fitness','local']],['speech-center','Логопедический центр',['medical','education','local']],['psychology-center','Психологический центр',['medical','education','local']],['hearing-center','Центр слухопротезирования',['medical','retail','local']],['optics-store','Салон оптики',['medical','retail','local']],['dental-lab','Зуботехническая лаборатория',['medical','manufacturing','b2b']],['orthopedic-salon','Ортопедический салон',['medical','retail','local']],['medical-distributor','Дистрибьютор медоборудования',['medical','supply','b2b']],['medical-maintenance','Сервис медицинского оборудования',['medical','electronics','b2b']],
['hvac-company','Вентиляция и кондиционирование',['facility','construction','industrial']],['fire-safety-company','Пожарная безопасность',['facility','security','construction']],['water-treatment','Водоподготовка и водоочистка',['facility','industrial','ecology']],['elevator-service','Лифтовая сервисная компания',['facility','industrial']],['boiler-house-service','Эксплуатация котельных',['facility','energy','industrial']],['electrical-lab','Электротехническая лаборатория',['facility','energy','certification']],['bms-integrator','Автоматизация зданий и BMS',['facility','it','industrial']],['vent-cleaning','Очистка вентиляции',['facility','cleaning','horeca']],['facade-service','Обслуживание фасадов',['facility','construction']],['roof-service','Кровельная компания',['construction','facility']],['snow-removal','Уборка и вывоз снега',['facility','cleaning','logistics']],['pest-control-b2b','Дезинсекция и пест-контроль для бизнеса',['facility','cleaning','horeca']],
['laser-cutting','Лазерная резка металла',['manufacturing','industrial']],['cnc-machining','ЧПУ обработка',['manufacturing','industrial']],['sheet-metal','Листовая металлообработка',['manufacturing','industrial']],['powder-coating','Порошковая покраска',['manufacturing','industrial']],['galvanizing','Гальваническое производство',['manufacturing','industrial']],['foundry','Литейное производство',['manufacturing','industrial']],['plastic-molding','Литьё пластмасс',['manufacturing','industrial']],['rubber-production','Резинотехнические изделия',['manufacturing','industrial']],['composite-production','Композитное производство',['manufacturing','industrial']],['packaging-production','Производство упаковки',['manufacturing','retail','ecommerce']],['label-production','Производство этикеток',['manufacturing','advertising','retail']],['pallet-production','Производство паллет и тары',['manufacturing','logistics']],['cold-storage','Холодильный склад',['logistics','food','industrial']],['industrial-refrigeration','Промышленный холод',['industrial','facility','food']],
['mobile-app-studio','Студия мобильных приложений',['it','b2b']],['one-c-integrator','Интегратор 1С',['it','finance','b2b']],['bitrix-integrator','Интегратор Битрикс24',['it','sales','b2b']],['crm-integrator','CRM-интегратор',['it','sales','b2b']],['erp-integrator','ERP-интегратор',['it','industrial','b2b']],['rpa-integrator','RPA и роботизация процессов',['it','b2b']],['chatbot-studio','Студия чат-ботов',['it','advertising','sales']],['voicebot-company','Голосовые роботы и телефония',['it','sales','telecom']],['data-center','Дата-центр',['it','telecom','facility']],['hosting-provider','Хостинг-провайдер',['it','telecom']],['ip-telephony','IP-телефония',['it','telecom','b2b']],['bi-integrator','BI и аналитика данных',['it','finance','b2b']],['data-engineering','Data Engineering и хранилища данных',['it','b2b']],['ux-research','UX-исследования',['it','design','consulting']],['product-design-studio','Продуктовый дизайн',['it','design','b2b']],
['audit-firm','Аудиторская компания',['finance','b2b']],['tax-consulting','Налоговый консалтинг',['finance','legal','b2b']],['insurance-broker','Страховой брокер',['finance','b2b']],['leasing-broker','Лизинговый брокер',['finance','auto','industrial']],['factoring-company','Факторинговая компания',['finance','b2b']],['mortgage-broker','Ипотечный брокер',['finance','realestate']],['ma-advisory','M&A консультанты',['finance','consulting','b2b']],['financial-modeling','Финансовое моделирование',['finance','consulting','b2b']],['management-accounting','Управленческий учёт на аутсорсе',['finance','b2b']],
['dance-school','Школа танцев',['education','fitness','local']],['art-school','Художественная школа и студия',['education','design','local']],['robotics-school','Школа робототехники',['education','it','local']],['programming-school','Школа программирования',['education','it','local']],['child-center','Детский развивающий центр',['education','local']],['summer-camp','Детский лагерь',['education','travel']],['corporate-university','Корпоративное обучение',['education','b2b']],['exam-center','Экзаменационный центр',['education','certification']],
['florist-shop','Цветочный магазин',['retail','local','events']],['gift-shop','Магазин подарков',['retail','local']],['stationery-store','Канцелярские товары',['retail','b2b']],['building-material-store','Магазин стройматериалов',['retail','construction']],['tool-store','Магазин инструмента',['retail','construction','industrial']],['electronics-store','Магазин электроники',['retail','electronics']],['farm-shop','Фермерский магазин',['retail','food','agro']],['dark-store','Даркстор',['retail','ecommerce','logistics']],
['customs-broker','Таможенный представитель',['logistics','supply','b2b']],['container-terminal','Контейнерный терминал',['logistics','industrial']],['last-mile','Последняя миля и доставка',['logistics','ecommerce']],['refrigerated-transport','Рефрижераторные перевозки',['logistics','food']],['oversized-cargo','Негабаритные перевозки',['logistics','industrial']],['rail-logistics','Железнодорожная логистика',['logistics','industrial']],['port-agent','Портовый агент',['logistics','industrial']],
['funeral-service','Ритуальные услуги',['local','service']],['monument-workshop','Изготовление памятников',['local','manufacturing']],['tailor-atelier','Ателье и пошив одежды',['local','manufacturing','retail']],['shoe-repair','Ремонт обуви',['local','retail']],['flower-delivery','Доставка цветов',['local','retail','logistics']],['translation-agency','Бюро переводов',['b2b','local','legal']],['notary-support','Сервис подготовки документов к нотариусу',['legal','local']],['archive-service','Архивное хранение документов',['b2b','logistics','legal']]
]);
addServices([
['ophthalmology-marketing','Продвижение офтальмологической клиники','service',['medical','advertising']],['medical-equipment-maintenance','Техническое обслуживание медицинского оборудования','work',['medical','electronics','b2b']],['medical-calibration','Поверка и контроль медицинского оборудования','service',['medical','certification']],['clinic-callcenter','Колл-центр для клиники','service',['medical','sales']],['clinic-crm','CRM и автоматизация клиники','service',['medical','it']],
['hvac-design','Проектирование вентиляции и кондиционирования','service',['facility','construction']],['hvac-install','Монтаж вентиляции и кондиционирования','work',['facility','construction']],['hvac-maintenance','Обслуживание вентиляции и кондиционирования','work',['facility','industrial']],['fire-audit','Аудит пожарной безопасности','service',['facility','security','certification']],['fire-system-install','Монтаж пожарной сигнализации','work',['facility','security','construction']],['water-treatment-design','Проектирование водоподготовки','service',['facility','industrial','ecology']],['water-treatment-install','Монтаж систем водоочистки','work',['facility','industrial']],['elevator-maintenance','Обслуживание лифтов','work',['facility','industrial']],['bms-integration','Внедрение BMS и диспетчеризации','work',['facility','it','industrial']],['electrical-testing','Электроизмерения и испытания','service',['facility','energy','certification']],['vent-cleaning-service','Очистка и дезинфекция вентиляции','service',['facility','cleaning','horeca']],
['laser-cut-service','Лазерная резка металла','work',['manufacturing','industrial']],['cnc-service','Механическая обработка на ЧПУ','work',['manufacturing','industrial']],['powder-coating-service','Порошковая покраска','work',['manufacturing','industrial']],['galvanic-service','Гальванические покрытия','work',['manufacturing','industrial']],['casting-service','Литьё деталей','work',['manufacturing','industrial']],['plastic-molding-service','Литьё пластмасс под давлением','work',['manufacturing','industrial']],['contract-packaging','Контрактная упаковка продукции','work',['manufacturing','retail','ecommerce']],['label-printing','Печать этикеток и маркировки','work',['manufacturing','advertising','retail']],['industrial-refrigeration-service','Монтаж и сервис промышленного холода','work',['industrial','facility','food']],
['mobile-app-development','Разработка мобильного приложения','service',['it']],['one-c-implementation','Внедрение и доработка 1С','service',['it','finance','b2b']],['bitrix-implementation','Внедрение Битрикс24','service',['it','sales','b2b']],['erp-implementation','Внедрение ERP','service',['it','industrial','b2b']],['rpa-automation','Роботизация бизнес-процессов RPA','service',['it','b2b']],['chatbot-development','Разработка чат-бота','service',['it','sales','advertising']],['voicebot-implementation','Внедрение голосового робота','service',['it','sales','telecom']],['ip-telephony-setup','Внедрение IP-телефонии','service',['it','telecom','b2b']],['bi-implementation','Внедрение BI-аналитики','service',['it','finance','b2b']],['data-warehouse','Разработка хранилища данных','service',['it','b2b']],['ux-research-service','UX-исследование продукта','service',['it','design','consulting']],['product-design-service','Дизайн цифрового продукта','service',['it','design']],
['financial-audit','Финансовый аудит','service',['finance','b2b']],['tax-audit','Налоговый аудит','service',['finance','legal','b2b']],['tax-consulting-service','Налоговое консультирование','service',['finance','legal','b2b']],['management-accounting-service','Постановка управленческого учёта','service',['finance','b2b']],['financial-model','Разработка финансовой модели','service',['finance','consulting','b2b']],['ma-support','Сопровождение сделки M&A','service',['finance','consulting','legal']],['insurance-selection','Подбор корпоративного страхования','service',['finance','b2b']],['leasing-selection','Подбор лизинга','service',['finance','auto','industrial']],
['dance-training','Обучение танцам','service',['education','fitness','local']],['art-training','Обучение рисованию и искусству','service',['education','design','local']],['robotics-training','Обучение робототехнике','service',['education','it','local']],['coding-training','Обучение программированию','service',['education','it']],['child-development','Развивающие занятия для детей','service',['education','local']],['corporate-training','Корпоративное обучение сотрудников','service',['education','b2b']],['exam-organization','Организация экзаменов и тестирования','service',['education','certification']],
['florist-supply','Поставка цветов и флористики','supply',['retail','events']],['gift-production','Изготовление корпоративных подарков','work',['retail','manufacturing','b2b']],['office-supply','Поставка канцтоваров в офис','supply',['retail','b2b']],['building-material-supply','Поставка строительных материалов','supply',['retail','construction']],['tool-supply','Поставка инструмента и оснастки','supply',['retail','industrial','construction']],['electronics-supply','Поставка электроники и оборудования','supply',['retail','electronics','b2b']],
['customs-clearance','Таможенное оформление','service',['logistics','supply','b2b']],['container-handling','Терминальная обработка контейнеров','service',['logistics','industrial']],['last-mile-delivery','Доставка последней мили','service',['logistics','ecommerce']],['reefer-transport','Рефрижераторная перевозка','service',['logistics','food']],['oversized-transport','Перевозка негабаритного груза','service',['logistics','industrial']],['rail-freight','Железнодорожная перевозка груза','service',['logistics','industrial']],['port-agency','Портовое агентирование','service',['logistics','industrial']],
['funeral-service-package','Организация ритуальных услуг','service',['local']],['monument-production','Изготовление и установка памятника','work',['local','manufacturing']],['tailoring','Пошив и ремонт одежды','work',['local','manufacturing']],['shoe-repair-service','Ремонт обуви','work',['local']],['flower-delivery-service','Доставка цветов','service',['local','retail','logistics']],['translation-service','Письменный перевод документов','service',['b2b','legal','local']],['interpreting-service','Устный перевод','service',['b2b','events','local']],['archive-storage-service','Архивное хранение документов','service',['b2b','logistics','legal']]
]);
})();
