(function () {
  'use strict';
  const RK = window.RKCatalog;
  if (!RK) return;

  function appendUnique(target, items) {
    const seen = new Set(target.map(function (x) { return x.slug; }));
    items.forEach(function (item) {
      if (seen.has(item.slug)) return;
      seen.add(item.slug);
      target.push(item);
    });
  }

  const extraNiches = [
    ['ophthalmology','Офтальмологическая клиника',['medical','local']],
    ['ent-clinic','ЛОР-клиника',['medical','local']],
    ['rehab-center','Реабилитационный центр',['medical','local']],
    ['diagnostic-center','Диагностический центр',['medical','local']],
    ['mri-center','Центр МРТ и КТ',['medical','local']],
    ['ultrasound-center','Центр УЗИ',['medical','local']],
    ['ivf-clinic','Клиника репродуктивной медицины',['medical','local']],
    ['psychology-center','Психологический центр',['medical','education','local']],
    ['speech-therapy','Логопедический центр',['medical','education','local']],
    ['massage-studio','Массажная студия',['beauty','fitness','local']],
    ['nutrition-center','Центр диетологии и нутрициологии',['medical','fitness','local']],
    ['dental-lab','Зуботехническая лаборатория',['medical','manufacturing','b2b']],
    ['orthodontics','Ортодонтическая клиника',['medical','local']],
    ['hair-salon','Парикмахерская',['beauty','local']],
    ['makeup-studio','Студия макияжа',['beauty','local']],
    ['tattoo-studio','Тату-студия',['beauty','local']],
    ['tanning-studio','Студия загара',['beauty','local']],
    ['gym','Тренажёрный зал',['fitness','local']],
    ['crossfit','Кроссфит-клуб',['fitness','local']],
    ['martial-arts','Школа единоборств',['fitness','education','local']],
    ['dance-studio','Танцевальная студия',['fitness','education','local']],
    ['swimming-school','Школа плавания',['fitness','education','local']],
    ['tennis-club','Теннисный клуб',['fitness','local']],
    ['football-academy','Футбольная академия',['fitness','education','local']],
    ['bar','Бар',['horeca','local']],
    ['pub','Паб',['horeca','local']],
    ['fast-food','Фастфуд',['horeca','food','local']],
    ['dark-kitchen','Dark kitchen',['horeca','food','ecommerce']],
    ['confectionery','Кондитерская',['horeca','food','local']],
    ['canteen','Столовая',['horeca','food','local']],
    ['banquet-hall','Банкетный зал',['horeca','events','local']],
    ['sanatorium','Санаторий',['travel','medical','horeca']],
    ['recreation-center','База отдыха',['travel','horeca']],
    ['glamping','Глэмпинг',['travel','horeca']],
    ['guest-house','Гостевой дом',['travel','horeca']],
    ['car-wash','Автомойка',['auto','local']],
    ['body-shop','Кузовной ремонт',['auto','local']],
    ['paint-shop','Покраска автомобилей',['auto','local']],
    ['auto-electric','Автоэлектрика',['auto','electronics','local']],
    ['truck-service','Грузовой автосервис',['auto','industrial','local']],
    ['motorcycle-service','Мотосервис',['auto','local']],
    ['tow-service','Эвакуатор и помощь на дороге',['auto','logistics','local']],
    ['taxi-fleet','Таксопарк',['auto','logistics']],
    ['fleet-management','Управление автопарком',['auto','logistics','b2b']],
    ['driving-school','Автошкола',['auto','education','local']],
    ['auto-parts-store','Магазин автозапчастей',['auto','retail']],
    ['tire-store','Магазин шин и дисков',['auto','retail']],
    ['property-appraisal','Оценочная компания',['realestate','finance','b2b']],
    ['cadastral-engineer','Кадастровый инженер',['realestate','construction','b2b']],
    ['geodesy','Геодезическая компания',['construction','industrial','b2b']],
    ['survey-company','Инженерные изыскания',['construction','industrial','b2b']],
    ['demolition','Демонтажная компания',['construction','industrial']],
    ['roofing','Кровельная компания',['construction','local']],
    ['windows','Оконная компания',['construction','manufacturing','local']],
    ['doors','Компания по дверям',['construction','manufacturing','local']],
    ['hvac','Вентиляция и кондиционирование',['construction','facility','industrial']],
    ['electrical-contractor','Электромонтажная компания',['construction','facility','industrial']],
    ['plumbing-contractor','Сантехническая компания',['construction','facility','local']],
    ['fire-systems','Пожарные системы',['construction','security','facility']],
    ['pool-company','Строительство бассейнов',['construction','local']],
    ['facade-company','Фасадная компания',['construction','industrial']],
    ['road-construction','Дорожное строительство',['construction','industrial']],
    ['concrete-company','Бетон и ЖБИ',['construction','manufacturing','industrial']],
    ['handyman','Мастер на час',['construction','local']],
    ['moving-company','Переезды и грузчики',['logistics','local']],
    ['mobile-development','Разработка мобильных приложений',['it','b2b']],
    ['software-development','Разработка программного обеспечения',['it','b2b']],
    ['one-c-integrator','1С-интегратор',['it','finance','b2b']],
    ['erp-integrator','ERP-интегратор',['it','industrial','b2b']],
    ['bi-company','BI и бизнес-аналитика',['it','consulting','b2b']],
    ['data-company','Data engineering и аналитика данных',['it','consulting','b2b']],
    ['chatbot-agency','Разработка чат-ботов',['it','advertising','b2b']],
    ['rpa-company','RPA и автоматизация процессов',['it','consulting','b2b']],
    ['hosting-provider','Хостинг-провайдер',['it','telecom','b2b']],
    ['cloud-provider','Облачный провайдер',['it','telecom','b2b']],
    ['managed-it','IT-аутсорсинг',['it','b2b']],
    ['computer-service','Компьютерный сервис',['it','electronics','local']],
    ['audit-firm','Аудиторская компания',['finance','b2b']],
    ['tax-consulting','Налоговый консалтинг',['finance','consulting','b2b']],
    ['cfo-outsourcing','Финансовый директор на аутсорсе',['finance','consulting','b2b']],
    ['management-accounting','Управленческий учёт',['finance','consulting','b2b']],
    ['payroll-outsourcing','Расчёт зарплаты на аутсорсе',['finance','hr','b2b']],
    ['hr-outsourcing','HR-аутсорсинг',['hr','b2b']],
    ['labor-safety','Охрана труда',['hr','certification','b2b']],
    ['personnel-records','Кадровое делопроизводство',['hr','b2b']],
    ['valuation-company','Оценка бизнеса и активов',['finance','consulting','b2b']],
    ['patent-agency','Патентное бюро',['legal','b2b']],
    ['trademark-agency','Регистрация товарных знаков',['legal','b2b']],
    ['compliance-company','Комплаенс-консалтинг',['legal','consulting','b2b']],
    ['privacy-consulting','Консалтинг по персональным данным',['legal','it','b2b']],
    ['business-broker','Бизнес-брокер',['consulting','sales','b2b']],
    ['corporate-training','Корпоративное обучение',['education','b2b']],
    ['exam-center','Центр подготовки к экзаменам',['education','local']],
    ['tutoring-center','Репетиторский центр',['education','local']],
    ['kids-center','Детский развивающий центр',['education','local']],
    ['robotics-school','Школа робототехники',['education','it','local']],
    ['coding-school','Школа программирования',['education','it','local']],
    ['music-school','Музыкальная школа',['education','local']],
    ['art-school','Художественная школа',['education','local']],
    ['clothing-store','Магазин одежды',['retail','ecommerce','local']],
    ['shoe-store','Магазин обуви',['retail','ecommerce','local']],
    ['cosmetics-store','Магазин косметики',['retail','beauty','ecommerce']],
    ['electronics-store','Магазин электроники',['retail','electronics','ecommerce']],
    ['jewelry-store','Ювелирный магазин',['retail','local']],
    ['flower-shop','Цветочный магазин',['retail','local']],
    ['gift-store','Магазин подарков',['retail','ecommerce','local']],
    ['book-store','Книжный магазин',['retail','local']],
    ['stationery-store','Канцелярский магазин',['retail','b2b']],
    ['optics-store','Салон оптики',['retail','medical','local']],
    ['sports-store','Магазин спортивных товаров',['retail','fitness','ecommerce']],
    ['baby-store','Магазин детских товаров',['retail','ecommerce']],
    ['building-materials','Магазин стройматериалов',['retail','construction','b2b']],
    ['plumbing-store','Магазин сантехники',['retail','construction']],
    ['lighting-store','Магазин освещения',['retail','construction']],
    ['packaging-production','Производство упаковки',['manufacturing','industrial','b2b']],
    ['plastic-production','Производство пластика',['manufacturing','industrial']],
    ['chemical-production','Химическое производство',['manufacturing','industrial']],
    ['pharma-production','Фармацевтическое производство',['manufacturing','medical','industrial']],
    ['woodworking','Деревообработка',['manufacturing','construction','industrial']],
    ['glass-production','Стекольное производство',['manufacturing','construction','industrial']],
    ['stone-production','Камнеобработка',['manufacturing','construction']],
    ['electronics-production','Производство электроники',['manufacturing','electronics','industrial']],
    ['machine-building','Машиностроение',['manufacturing','industrial']],
    ['auto-parts-production','Производство автокомпонентов',['manufacturing','auto','industrial']],
    ['cosmetics-production','Производство косметики',['manufacturing','beauty']],
    ['beverage-production','Производство напитков',['manufacturing','food']],
    ['trucking','Грузовая транспортная компания',['logistics','auto','b2b']],
    ['refrigerated-logistics','Рефрижераторные перевозки',['logistics','food','b2b']],
    ['last-mile','Последняя миля и доставка',['logistics','ecommerce']],
    ['customs-broker','Таможенный представитель',['logistics','supply','b2b']],
    ['container-logistics','Контейнерные перевозки',['logistics','industrial','b2b']],
    ['rail-logistics','Железнодорожные перевозки',['logistics','industrial','b2b']],
    ['air-cargo','Авиагрузоперевозки',['logistics','b2b']],
    ['greenhouse','Тепличное хозяйство',['agro','food']],
    ['dairy-farm','Молочная ферма',['agro','food']],
    ['poultry-farm','Птицефабрика',['agro','food','industrial']],
    ['fish-farm','Рыбное хозяйство',['agro','food']],
    ['beekeeping','Пчеловодство',['agro','food']],
    ['grain-company','Зерновая компания',['agro','food','supply']],
    ['agro-machinery','Сельхозтехника и оборудование',['agro','industrial','retail']],
    ['fertilizer-company','Удобрения и агрохимия',['agro','supply','industrial']],
    ['wedding-agency','Свадебное агентство',['events','local']],
    ['conference-organizer','Организатор конференций',['events','b2b']],
    ['exhibition-contractor','Выставочные стенды',['events','construction','b2b']],
    ['podcast-studio','Подкаст-студия',['media','local']],
    ['influencer-agency','Агентство блогеров',['advertising','media','b2b']],
    ['pr-agency','PR-агентство',['advertising','media','b2b']],
    ['design-agency','Дизайн-агентство',['design','advertising','b2b']],
    ['translation-agency','Бюро переводов',['consulting','b2b']],
    ['disinfection','Дезинфекция и дезинсекция',['cleaning','facility','local']],
    ['waste-removal','Вывоз отходов',['ecology','logistics','facility']],
    ['snow-removal','Уборка снега',['cleaning','facility','local']],
    ['elevator-service','Обслуживание лифтов',['facility','industrial']],
    ['water-treatment','Водоочистка и водоподготовка',['facility','industrial']],
    ['solar-company','Солнечная энергетика',['energy','construction','industrial']],
    ['electrical-lab','Электролаборатория',['energy','certification','industrial']],
    ['ev-charging','Зарядные станции для электромобилей',['energy','auto','construction']],
    ['insurance-agency','Страховое агентство',['finance','sales']],
    ['insurance-broker','Страховой брокер',['finance','consulting','b2b']],
    ['leasing-broker','Лизинговый брокер',['finance','sales','b2b']],
    ['funeral-service','Ритуальная служба',['local','service']],
    ['tailor','Ателье',['local','manufacturing']],
    ['shoe-repair','Ремонт обуви',['local']],
    ['copy-center','Копировальный центр',['local','printing']],
    ['office-furniture','Офисная мебель',['manufacturing','b2b','retail']]
  ].map(function (x) { return { slug:x[0], name:x[1], tags:x[2] }; });

  const extraServices = [
    ['landing','Разработка лендинга','service',['it','advertising','b2b']],
    ['ecommerce-dev','Разработка интернет-магазина','service',['it','ecommerce','retail']],
    ['mobile-app','Разработка мобильного приложения','service',['it']],
    ['ux-ui','UX/UI-дизайн','service',['it','design']],
    ['logo','Разработка логотипа','service',['design','advertising']],
    ['brandbook','Разработка брендбука','service',['design','advertising']],
    ['seo-audit','SEO-аудит сайта','service',['it','advertising']],
    ['local-seo','Локальное SEO','service',['advertising','local']],
    ['yandex-direct','Настройка Яндекс Директ','service',['advertising']],
    ['vk-ads','Реклама ВКонтакте','service',['advertising']],
    ['telegram-ads','Реклама в Telegram','service',['advertising']],
    ['influencer-marketing','Реклама у блогеров','service',['advertising','media']],
    ['pr','PR-сопровождение','service',['advertising','media']],
    ['web-analytics','Настройка веб-аналитики','service',['advertising','it']],
    ['cro','Повышение конверсии сайта','service',['advertising','it','sales']],
    ['copywriting','Копирайтинг','service',['advertising','media']],
    ['article-writing','Экспертные статьи и контент','service',['advertising','media','education']],
    ['presentation','Разработка презентации','service',['design','sales','consulting']],
    ['pitch-deck','Разработка pitch deck','service',['design','sales','consulting']],
    ['chatbot','Разработка чат-бота','service',['it','sales','advertising']],
    ['ai-assistant','Внедрение ИИ-ассистента','service',['it','sales','consulting']],
    ['one-c','Внедрение 1С','service',['it','finance','manufacturing','retail']],
    ['one-c-support','Сопровождение 1С','service',['it','finance','manufacturing','retail']],
    ['erp','Внедрение ERP','service',['it','industrial','manufacturing']],
    ['bi','Внедрение BI-аналитики','service',['it','finance','consulting']],
    ['cloud-migration','Миграция в облако','service',['it','telecom']],
    ['server-admin','Администрирование серверов','service',['it','telecom']],
    ['it-outsourcing','IT-аутсорсинг','service',['it','b2b']],
    ['network-install','Монтаж компьютерных сетей','work',['it','telecom','construction']],
    ['backup','Резервное копирование и аварийное восстановление','service',['it','security']],
    ['data-migration','Миграция данных','service',['it']],
    ['rpa','Роботизация бизнес-процессов','service',['it','consulting']],
    ['website-support','Техническая поддержка сайта','service',['it','advertising']],
    ['app-support','Поддержка мобильного приложения','service',['it']],
    ['hr-records','Кадровое делопроизводство','service',['hr','b2b']],
    ['payroll','Расчёт заработной платы','service',['hr','finance','b2b']],
    ['labor-protection','Аутсорсинг охраны труда','service',['hr','certification','b2b']],
    ['sout','Специальная оценка условий труда','service',['hr','certification','industrial']],
    ['staff-assessment','Оценка персонала','service',['hr','consulting']],
    ['corporate-training-service','Корпоративное обучение сотрудников','service',['hr','education','b2b']],
    ['employer-brand','Развитие бренда работодателя','service',['hr','advertising']],
    ['tax-reporting','Подготовка налоговой отчётности','service',['finance','b2b']],
    ['tax-consult','Налоговая консультация','service',['finance','consulting']],
    ['audit','Аудит бухгалтерской отчётности','service',['finance','b2b']],
    ['management-accounting-service','Постановка управленческого учёта','service',['finance','consulting']],
    ['cfo','Функция финансового директора','service',['finance','consulting']],
    ['contract-audit','Юридический аудит договоров','service',['legal','b2b']],
    ['claims','Претензионная работа','service',['legal','b2b']],
    ['court','Представительство в суде','service',['legal','b2b']],
    ['business-registration','Регистрация ИП и ООО','service',['legal','consulting']],
    ['trademark','Регистрация товарного знака','service',['legal','advertising']],
    ['privacy','Сопровождение по 152-ФЗ','service',['legal','it','b2b']],
    ['license','Лицензионное сопровождение','service',['legal','certification','medical']],
    ['compliance','Комплаенс-аудит','service',['legal','consulting','b2b']],
    ['general-design','Проектирование объекта','service',['construction']],
    ['engineering-survey','Инженерные изыскания','service',['construction','industrial']],
    ['geodesy-service','Геодезические работы','work',['construction','industrial']],
    ['cadastral','Кадастровые работы','service',['construction','realestate']],
    ['demolition-service','Демонтажные работы','work',['construction']],
    ['roofing-service','Кровельные работы','work',['construction']],
    ['facade-service','Фасадные работы','work',['construction']],
    ['electrical','Электромонтажные работы','work',['construction','facility']],
    ['plumbing','Сантехнические работы','work',['construction','facility']],
    ['ventilation','Монтаж вентиляции','work',['construction','facility','industrial']],
    ['air-conditioning','Монтаж кондиционирования','work',['construction','facility']],
    ['fire-alarm','Монтаж пожарной сигнализации','work',['construction','security','facility']],
    ['low-voltage','Монтаж слаботочных систем','work',['construction','security','it']],
    ['windows-install','Монтаж окон','work',['construction','local']],
    ['doors-install','Монтаж дверей','work',['construction','local']],
    ['landscape-service','Ландшафтные работы','work',['construction','agro','local']],
    ['post-construction-clean','Послестроительный клининг','service',['construction','cleaning']],
    ['office-supply','Поставка офисных товаров','supply',['b2b','retail']],
    ['medical-supply','Поставка медицинских расходников','supply',['medical']],
    ['industrial-supply-extra','Поставка промышленной оснастки','supply',['industrial','manufacturing']],
    ['packaging-supply','Поставка упаковки','supply',['manufacturing','retail','ecommerce','food']],
    ['electronics-supply','Поставка электроники и компьютерной техники','supply',['it','electronics','b2b']],
    ['furniture-supply','Поставка мебели','supply',['retail','construction','b2b']],
    ['courier','Курьерская доставка','service',['logistics','ecommerce','local']],
    ['last-mile-service','Доставка последней мили','service',['logistics','ecommerce']],
    ['moving','Организация переезда','service',['logistics','local']],
    ['cold-chain','Рефрижераторная перевозка','service',['logistics','food','medical']],
    ['container','Контейнерная перевозка','service',['logistics','industrial']],
    ['rail','Железнодорожная перевозка','service',['logistics','industrial']],
    ['air-freight','Авиаперевозка груза','service',['logistics']],
    ['customs-declaration','Таможенное декларирование','service',['logistics','supply']],
    ['supplier-search','Поиск и проверка поставщиков','service',['procurement','supply','b2b']],
    ['china-inspection','Инспекция товара в Китае','service',['supply','logistics']],
    ['retail-audit','Аудит розничных точек','service',['retail','consulting']],
    ['pricing','Управление ценами и ассортиментом','service',['retail','ecommerce','consulting']],
    ['marketplace-account','Полное ведение кабинета маркетплейса','service',['ecommerce']],
    ['marketplace-content','Контент для карточек маркетплейса','service',['ecommerce','design','media']],
    ['marketplace-logistics','Логистика маркетплейсов','service',['ecommerce','logistics']],
    ['production-audit','Производственный аудит','service',['manufacturing','industrial','consulting']],
    ['equipment-install','Монтаж промышленного оборудования','work',['manufacturing','industrial']],
    ['equipment-commissioning','Пусконаладочные работы','work',['manufacturing','industrial']],
    ['maintenance-contract','Сервисное обслуживание оборудования','work',['industrial','electronics','medical']],
    ['contract-production','Контрактное производство','work',['manufacturing']],
    ['quality-control','Контроль качества партии товара','service',['manufacturing','supply']],
    ['certification-service','Сертификация продукции','service',['certification','manufacturing','supply']],
    ['declaration-service','Оформление деклараций соответствия','service',['certification','manufacturing','supply']],
    ['event-production','Техническое производство мероприятия','service',['events']],
    ['venue-rent','Аренда площадки для мероприятия','rent',['events']],
    ['sound-rent','Аренда звукового оборудования','rent',['events']],
    ['light-rent','Аренда светового оборудования','rent',['events']],
    ['event-decoration','Оформление и декор мероприятия','service',['events','design']],
    ['exhibition-stand','Изготовление выставочного стенда','work',['events','construction']],
    ['fire-safety-service','Обслуживание систем пожарной безопасности','work',['facility','security']],
    ['access-control','Монтаж системы контроля доступа','work',['facility','security','it']],
    ['pest-control','Дезинсекция и дератизация','service',['cleaning','facility','local']],
    ['waste-service','Вывоз и утилизация отходов','service',['ecology','facility','logistics']],
    ['snow-service','Механизированная уборка снега','service',['cleaning','facility']],
    ['elevator-maintenance','Техническое обслуживание лифтов','work',['facility','industrial']],
    ['water-treatment-service','Монтаж и обслуживание водоочистки','work',['facility','industrial']],
    ['solar-install','Монтаж солнечных электростанций','work',['energy','construction']],
    ['electrical-testing','Электроизмерительные работы','work',['energy','certification','industrial']],
    ['ev-charger-install','Монтаж зарядных станций','work',['energy','auto','construction']],
    ['agro-consult','Агрономический консалтинг','service',['agro']],
    ['agro-machinery-service','Обслуживание сельхозтехники','work',['agro','industrial']],
    ['seed-supply','Поставка семян и посадочного материала','supply',['agro']],
    ['fertilizer-supply','Поставка удобрений','supply',['agro']],
    ['feed-supply','Поставка кормов','supply',['agro','food']],
    ['translation','Письменный перевод','service',['consulting','b2b']],
    ['interpretation','Устный перевод','service',['consulting','events','b2b']],
    ['document-translation','Перевод документов','service',['consulting','legal']],
    ['business-valuation','Оценка бизнеса','service',['finance','consulting']],
    ['property-valuation','Оценка недвижимости','service',['finance','realestate']],
    ['franchise-audit','Аудит франшизы','service',['franchise','consulting']],
    ['insurance-selection','Подбор страхования для бизнеса','service',['finance','consulting']],
    ['leasing-selection','Подбор лизинга','service',['finance','sales']]
  ].map(function (x) { return { slug:x[0], name:x[1], mode:x[2], tags:x[3] }; });

  appendUnique(RK.niches, extraNiches);
  appendUnique(RK.services, extraServices);

  RK.extraMeta = {
    extraNiches: extraNiches.length,
    extraServices: extraServices.length,
    totalNiches: RK.niches.length,
    totalServices: RK.services.length
  };
})();
