(function(){
'use strict';
const RK=window.RKCatalog;if(!RK)return;
function appendUnique(target,items){const seen=new Set(target.map(x=>x.slug));items.forEach(item=>{if(seen.has(item.slug))return;seen.add(item.slug);target.push(item)})}
const niches=[
['bank-b2b','Банк для бизнеса',['finance','b2b']],['payment-service','Платёжный сервис',['finance','it','ecommerce']],['acquiring-provider','Эквайринг и платёжная инфраструктура',['finance','it','retail']],['leasing-company','Лизинговая компания',['finance','auto','industrial','b2b']],['factoring-service','Факторинговый сервис',['finance','b2b']],['credit-broker','Кредитный брокер для бизнеса',['finance','sales','b2b']],['accounting-platform','Онлайн-бухгалтерия',['finance','it','b2b']],['edoc-platform','Сервис электронного документооборота',['finance','it','b2b']],['cash-register-provider','Онлайн-кассы и ОФД',['finance','it','retail']],['debt-service','Сервис взыскания дебиторской задолженности',['finance','legal','b2b']],
['oil-service','Нефтесервисная компания',['industrial','energy','b2b']],['oil-equipment','Нефтегазовое оборудование',['industrial','energy','manufacturing']],['gas-service','Газовое хозяйство и обслуживание',['energy','facility','industrial']],['mining-company','Горнодобывающая компания',['industrial','manufacturing']],['quarry','Карьер и добыча нерудных материалов',['industrial','construction']],['drilling-company','Буровая компания',['industrial','construction','energy']],['geology-company','Геологоразведочная компания',['industrial','consulting']],['mining-equipment','Горное оборудование',['industrial','manufacturing']],['laboratory-industrial','Промышленная лаборатория',['industrial','certification']],['ndt-lab','Лаборатория неразрушающего контроля',['industrial','certification']],
['power-contractor','Электросетевая подрядная компания',['energy','construction','industrial']],['substation-service','Обслуживание подстанций',['energy','industrial']],['generator-service','Обслуживание генераторов',['energy','industrial']],['boiler-service','Обслуживание котельных',['energy','facility','industrial']],['heat-supply','Теплоснабжающая компания',['energy','facility']],['water-utility','Водоканал и водоснабжение',['facility','industrial']],['energy-equipment','Энергетическое оборудование',['energy','manufacturing']],['ups-company','ИБП и системы бесперебойного питания',['energy','electronics','b2b']],['battery-company','Промышленные аккумуляторы',['energy','electronics','industrial']],['electrical-panel','Производство электрощитового оборудования',['energy','manufacturing','industrial']],
['marine-logistics','Морская логистика',['logistics','industrial']],['port-operator','Портовый оператор',['logistics','industrial']],['river-shipping','Речные перевозки',['logistics','industrial']],['shipping-agent','Морской агент',['logistics','b2b']],['freight-forwarder','Международный экспедитор',['logistics','b2b']],['airline-cargo-agent','Агент грузовых авиаперевозок',['logistics','b2b']],['bus-company','Автобусный перевозчик',['logistics','auto']],['employee-shuttle','Корпоративная развозка сотрудников',['logistics','hr','b2b']],['taxi-service-b2b','Корпоративное такси',['logistics','auto','b2b']],['fleet-rental','Корпоративная аренда автопарка',['auto','rent','b2b']],
['telecom-integrator','Телеком-интегратор',['telecom','it','b2b']],['internet-provider-b2b','Интернет-провайдер для бизнеса',['telecom','it','b2b']],['sip-provider','SIP-телефония',['telecom','it','sales']],['satellite-provider','Спутниковая связь',['telecom','industrial']],['radio-company','Профессиональная радиосвязь',['telecom','security','industrial']],['fiber-contractor','Строительство ВОЛС',['telecom','construction']],['network-operator','Оператор связи',['telecom','it']],['iot-company','IoT-интегратор',['it','industrial','telecom']],['smart-building','Умное здание и диспетчеризация',['it','facility','construction']],['access-control-company','СКУД и контроль доступа',['security','it','facility']],
['lab-equipment','Лабораторное оборудование',['medical','industrial','manufacturing']],['lab-reagents','Лабораторные реагенты',['medical','supply','industrial']],['cleanroom-company','Чистые помещения',['medical','construction','industrial']],['sterilization-equipment','Стерилизационное оборудование',['medical','industrial']],['clinic-furniture','Медицинская мебель',['medical','manufacturing']],['dental-materials','Стоматологические материалы',['medical','supply']],['optical-equipment','Офтальмологическое оборудование',['medical','industrial']],['rehab-equipment','Реабилитационное оборудование',['medical','fitness']],['pharmacy-chain','Аптечная сеть',['medical','retail']],['pharma-distributor','Фармдистрибьютор',['medical','supply','b2b']],
['bakery-equipment','Оборудование для пекарен',['horeca','industrial']],['restaurant-equipment','Ресторанное оборудование',['horeca','industrial']],['coffee-equipment','Кофейное оборудование',['horeca','industrial']],['professional-kitchen','Профессиональные кухни',['horeca','construction','industrial']],['horeca-distributor','HoReCa-дистрибьютор',['horeca','supply','b2b']],['food-packaging','Пищевая упаковка',['food','manufacturing','supply']],['food-lab','Пищевая лаборатория',['food','certification']],['cold-storage','Холодильные склады',['food','logistics','industrial']],['refrigeration-company','Промышленный холод',['food','industrial','facility']],['vending-company','Вендинговая компания',['retail','horeca','b2b']],
['laundry-equipment','Прачечное оборудование',['cleaning','industrial','horeca']],['commercial-laundry','Промышленная прачечная',['cleaning','horeca','b2b']],['uniform-service','Аренда и обслуживание спецодежды',['rent','cleaning','industrial']],['workwear-production','Производство спецодежды',['manufacturing','industrial']],['ppe-supplier','Средства индивидуальной защиты',['supply','industrial','hr']],['industrial-cleaning','Промышленный клининг',['cleaning','industrial']],['tank-cleaning','Очистка резервуаров',['cleaning','industrial','energy']],['vent-cleaning','Очистка вентиляции',['cleaning','facility','horeca']],['pest-control-b2b','Пест-контроль для бизнеса',['cleaning','horeca','facility']],['facility-outsourcing','Комплексный facility-аутсорсинг',['facility','b2b']],
['packaging-design','Дизайн упаковки',['design','manufacturing','advertising']],['flexo-printing','Флексопечать',['printing','manufacturing']],['offset-printing','Офсетная печать',['printing','advertising']],['large-format-printing','Широкоформатная печать',['printing','advertising']],['promo-production','Производство рекламных материалов',['advertising','manufacturing']],['souvenir-production','Сувенирная продукция',['manufacturing','advertising']],['textile-printing','Печать на текстиле',['manufacturing','printing']],['embroidery-company','Машинная вышивка',['manufacturing','printing']],['pos-materials','POS-материалы и торговое оборудование',['retail','manufacturing','advertising']],['exhibition-production','Производство выставочных конструкций',['events','manufacturing','construction']],
['industrial-design','Промышленный дизайн',['design','manufacturing']],['cad-bureau','CAD/конструкторское бюро',['design','industrial']],['reverse-engineering','Реверс-инжиниринг',['industrial','manufacturing','consulting']],['prototyping','Прототипирование и 3D-печать',['manufacturing','design']],['metrology','Метрологическая служба',['certification','industrial']],['calibration-lab','Калибровочная лаборатория',['certification','industrial']],['testing-center','Испытательный центр',['certification','industrial']],['certification-lab','Орган по сертификации',['certification','b2b']],['industrial-inspection','Техническая инспекция',['certification','industrial']],['supplier-audit','Аудит поставщиков',['consulting','supply','industrial']],
['parking-operator','Оператор парковок',['facility','auto','local']],['car-park-service','Обслуживание парковок',['facility','auto']],['ev-network','Сеть зарядных станций',['energy','auto','it']],['car-subscription','Автомобиль по подписке',['auto','rent','it']],['fleet-telematics','Телематика автопарка',['auto','it','logistics']],['gps-monitoring','GPS/ГЛОНАСС мониторинг транспорта',['auto','it','logistics']],['fuel-card-service','Топливные карты для бизнеса',['auto','finance','b2b']],['corporate-car-service','Корпоративное обслуживание автопарка',['auto','b2b']],['truck-parts','Запчасти для грузовиков',['auto','retail','industrial']],['special-equipment-parts','Запчасти для спецтехники',['industrial','construction','retail']]
].map(x=>({slug:x[0],name:x[1],tags:x[2]}));
const services=[
['business-acquiring','Подключение торгового эквайринга','service',['finance','retail','ecommerce']],['internet-acquiring','Подключение интернет-эквайринга','service',['finance','ecommerce','it']],['payment-integration','Интеграция платёжной системы','service',['finance','it','ecommerce']],['leasing-selection','Подбор и оформление лизинга','service',['finance','auto','industrial']],['factoring','Факторинговое обслуживание','service',['finance','b2b']],['bank-guarantee','Получение банковской гарантии','service',['finance','procurement','b2b']],['cash-register','Поставка и настройка онлайн-кассы','supply',['finance','retail','it']],['edo-connect','Подключение ЭДО','service',['finance','it','b2b']],
['industrial-maintenance','Плановое обслуживание промышленного оборудования','work',['industrial','manufacturing']],['emergency-repair','Аварийный ремонт оборудования','work',['industrial','manufacturing']],['commissioning','Пусконаладочные работы','work',['industrial','construction']],['equipment-installation','Монтаж промышленного оборудования','work',['industrial','construction']],['equipment-modernization','Модернизация оборудования','work',['industrial','manufacturing']],['ndt','Неразрушающий контроль','service',['industrial','certification']],['metrology-service','Метрологическое обслуживание','service',['industrial','certification']],['calibration','Калибровка средств измерений','service',['industrial','certification']],['industrial-inspection-service','Техническая инспекция оборудования','service',['industrial','certification']],['reverse-engineering-service','Реверс-инжиниринг детали или узла','service',['industrial','manufacturing','design']],
['power-installation','Монтаж электрооборудования','work',['energy','construction']],['substation-maintenance','Техническое обслуживание подстанции','work',['energy','industrial']],['generator-maintenance','Обслуживание дизель-генераторов','work',['energy','industrial']],['boiler-maintenance','Обслуживание котельной','work',['energy','facility']],['energy-equipment-supply','Поставка энергетического оборудования','supply',['energy','industrial']],['ups-supply','Поставка ИБП','supply',['energy','electronics']],['battery-supply','Поставка промышленных аккумуляторов','supply',['energy','electronics']],['electrical-audit','Электротехнический аудит','service',['energy','certification']],
['sea-freight','Морская перевозка груза','service',['logistics','industrial']],['river-freight','Речная перевозка груза','service',['logistics','industrial']],['port-handling','Портовая обработка груза','service',['logistics','industrial']],['freight-forwarding','Международное экспедирование','service',['logistics','b2b']],['corporate-taxi','Корпоративное такси','service',['logistics','auto','b2b']],['employee-transport','Развозка сотрудников','service',['logistics','hr','b2b']],['fleet-rent','Долгосрочная аренда автопарка','rent',['auto','b2b']],['fleet-management-service','Управление корпоративным автопарком','service',['auto','logistics','b2b']],['gps-install','Установка GPS/ГЛОНАСС мониторинга','work',['auto','it','logistics']],['fuel-cards','Топливные карты и контроль расходов','service',['auto','finance','b2b']],
['fiber-install','Строительство и монтаж ВОЛС','work',['telecom','construction']],['sip-telephony','Подключение SIP-телефонии','service',['telecom','it','sales']],['corporate-internet','Подключение интернета для офиса','service',['telecom','it','b2b']],['radio-install','Монтаж профессиональной радиосвязи','work',['telecom','security']],['iot-integration','Внедрение IoT-мониторинга','service',['it','industrial','telecom']],['smart-building-integration','Автоматизация и диспетчеризация здания','service',['it','facility','construction']],['access-control-install','Монтаж СКУД','work',['security','facility','it']],
['medical-equipment-supply','Поставка медицинского оборудования','supply',['medical','industrial']],['medical-equipment-install','Монтаж медицинского оборудования','work',['medical','industrial']],['medical-equipment-maintenance','Техническое обслуживание медицинского оборудования','work',['medical','industrial']],['lab-equipment-supply','Поставка лабораторного оборудования','supply',['medical','industrial']],['reagent-supply','Поставка лабораторных реагентов','supply',['medical']],['cleanroom-design','Проектирование чистых помещений','service',['medical','construction']],['cleanroom-install','Монтаж чистых помещений','work',['medical','construction']],['dental-material-supply','Поставка стоматологических материалов','supply',['medical']],['pharma-logistics','Логистика фармпродукции','service',['medical','logistics']],
['restaurant-equipment-supply','Поставка ресторанного оборудования','supply',['horeca','industrial']],['restaurant-equipment-install','Монтаж ресторанного оборудования','work',['horeca','industrial']],['coffee-machine-rent','Аренда кофемашин','rent',['horeca','b2b']],['coffee-machine-service','Обслуживание кофемашин','work',['horeca','industrial']],['refrigeration-install','Монтаж холодильного оборудования','work',['horeca','food','industrial']],['refrigeration-service','Обслуживание холодильного оборудования','work',['horeca','food','industrial']],['food-lab-testing','Лабораторные испытания пищевой продукции','service',['food','certification']],['horeca-supply','Комплексная поставка для HoReCa','supply',['horeca','food']],
['industrial-laundry','Промышленная стирка текстиля','service',['cleaning','horeca']],['uniform-rental','Аренда и обслуживание спецодежды','rent',['industrial','cleaning']],['ppe-supply','Поставка СИЗ','supply',['industrial','hr']],['industrial-cleaning-service','Промышленная уборка','service',['cleaning','industrial']],['tank-cleaning-service','Очистка резервуаров и ёмкостей','work',['cleaning','industrial','energy']],['vent-cleaning-service','Очистка вентиляционных систем','work',['cleaning','facility','horeca']],['facility-outsourcing-service','Комплексное обслуживание объекта','service',['facility','b2b']],
['package-design','Разработка дизайна упаковки','service',['design','manufacturing','advertising']],['packaging-production-service','Изготовление упаковки','work',['manufacturing','supply']],['label-printing','Печать этикеток','work',['printing','manufacturing']],['large-format-print','Широкоформатная печать','work',['printing','advertising']],['promo-materials','Изготовление рекламных материалов','work',['advertising','manufacturing']],['souvenir-production-service','Изготовление сувенирной продукции','work',['manufacturing','advertising']],['pos-production','Изготовление POS-материалов','work',['retail','manufacturing','advertising']],['exhibition-stand','Производство и монтаж выставочного стенда','work',['events','construction']],
['prototype-production','Изготовление прототипа','work',['manufacturing','design']],['3d-print','3D-печать деталей','work',['manufacturing','design']],['cad-design','Разработка конструкторской документации','service',['design','industrial']],['supplier-inspection','Инспекция производства поставщика','service',['consulting','supply','industrial']],['factory-audit','Аудит производства','service',['consulting','manufacturing','industrial']],['quality-system','Внедрение системы менеджмента качества','service',['consulting','certification','industrial']],
['parking-management','Управление парковкой','service',['facility','auto']],['parking-equipment','Поставка парковочного оборудования','supply',['facility','auto','electronics']],['ev-station-install','Монтаж зарядной станции','work',['energy','auto','construction']],['ev-station-service','Обслуживание зарядных станций','work',['energy','auto']],['truck-parts-supply','Поставка запчастей для грузовиков','supply',['auto','industrial']],['special-parts-supply','Поставка запчастей для спецтехники','supply',['industrial','construction']]
].map(x=>({slug:x[0],name:x[1],mode:x[2],tags:x[3]}));
appendUnique(RK.niches,niches);appendUnique(RK.services,services);
RK.extensionMeta=RK.extensionMeta||[];RK.extensionMeta.push({name:'catalog-extra-3',niches:niches.length,services:services.length});
})();
