(function () {
  'use strict';
  const RK = window.RKCatalog;
  if (!RK) return;

  function appendUnique(target, items) {
    const seen = new Set(target.map(function (x) { return x.slug; }));
    items.forEach(function (item) {
      if (seen.has(item.slug)) return;
      seen.add(item.slug);
      target.push(item);
    });
  }

  const niches = [
    ['allergy-clinic','Аллергологическая клиника',['medical','local']],
    ['cardiology-clinic','Кардиологическая клиника',['medical','local']],
    ['neurology-clinic','Неврологическая клиника',['medical','local']],
    ['dermatology-clinic','Дерматологическая клиника',['medical','beauty','local']],
    ['urology-clinic','Урологическая клиника',['medical','local']],
    ['gynecology-clinic','Гинекологическая клиника',['medical','local']],
    ['pediatrics-clinic','Детская клиника',['medical','local']],
    ['endocrinology-clinic','Эндокринологическая клиника',['medical','local']],
    ['orthopedics-clinic','Ортопедическая клиника',['medical','local']],
    ['phlebology-clinic','Флебологическая клиника',['medical','local']],
    ['dialysis-center','Диализный центр',['medical','local']],
    ['hearing-center','Центр слуха и слуховых аппаратов',['medical','retail','local']],
    ['medical-equipment-company','Медицинское оборудование',['medical','industrial','b2b']],
    ['dental-equipment-company','Стоматологическое оборудование',['medical','industrial','b2b']],
    ['medical-distributor','Дистрибьютор медизделий',['medical','supply','b2b']],
    ['laser-hair-removal','Студия лазерной эпиляции',['beauty','local']],
    ['epilation-studio','Студия эпиляции',['beauty','local']],
    ['permanent-makeup','Студия перманентного макияжа',['beauty','local']],
    ['lash-studio','Студия наращивания ресниц',['beauty','local']],
    ['beauty-school','Школа мастеров красоты',['beauty','education','local']],
    ['pilates-studio','Студия пилатеса',['fitness','local']],
    ['stretching-studio','Студия растяжки',['fitness','local']],
    ['cycling-studio','Сайкл-студия',['fitness','local']],
    ['personal-training','Студия персональных тренировок',['fitness','local']],
    ['sports-medicine','Центр спортивной медицины',['fitness','medical','local']],
    ['brewery','Пивоварня',['food','manufacturing','horeca']],
    ['winery','Винодельня',['food','manufacturing']],
    ['meat-production','Мясное производство',['food','manufacturing','industrial']],
    ['fish-processing','Рыбопереработка',['food','manufacturing','industrial']],
    ['dairy-production','Молочное производство',['food','manufacturing','industrial']],
    ['frozen-food','Производство полуфабрикатов',['food','manufacturing']],
    ['restaurant-chain','Сеть ресторанов',['horeca','franchise','retail']],
    ['coffee-chain','Сеть кофеен',['horeca','franchise','retail']],
    ['food-court','Фуд-корт',['horeca','retail','realestate']],
    ['hotel-management','Управляющая компания отелей',['horeca','travel','facility','b2b']],
    ['travel-tech','TravelTech-сервис',['travel','it','b2b']],
    ['excursion-company','Экскурсионная компания',['travel','events','local']],
    ['guide-service','Сервис гидов и экскурсий',['travel','local']],
    ['bus-tour-company','Автобусные туры',['travel','logistics']],
    ['yacht-rental','Аренда яхт и катеров',['travel','rent']],
    ['car-sharing','Каршеринг',['auto','rent','it']],
    ['truck-rental','Аренда грузового транспорта',['auto','rent','logistics']],
    ['special-equipment-rental','Аренда спецтехники',['construction','rent','industrial']],
    ['forklift-rental','Аренда погрузчиков',['logistics','rent','industrial']],
    ['generator-rental','Аренда генераторов',['energy','rent','construction']],
    ['tool-rental','Прокат инструмента',['construction','rent','local']],
    ['auto-glass','Автостёкла',['auto','retail','local']],
    ['car-audio','Автозвук и дополнительное оборудование',['auto','electronics','local']],
    ['car-alarm','Автосигнализации',['auto','security','electronics','local']],
    ['wheel-repair','Ремонт дисков',['auto','local']],
    ['engine-repair','Ремонт двигателей',['auto','industrial','local']],
    ['transmission-repair','Ремонт коробок передач',['auto','industrial','local']],
    ['commercial-vehicle-service','Сервис коммерческого транспорта',['auto','industrial','b2b']],
    ['used-car-dealer','Автосалон автомобилей с пробегом',['auto','retail']],
    ['car-auction','Автомобильный аукцион',['auto','retail','sales']],
    ['mortgage-broker','Ипотечный брокер',['realestate','finance','sales']],
    ['rental-agency','Агентство аренды недвижимости',['realestate','rent','local']],
    ['commercial-real-estate','Коммерческая недвижимость',['realestate','b2b']],
    ['industrial-real-estate','Индустриальная недвижимость',['realestate','industrial','b2b']],
    ['warehouse-real-estate','Складская недвижимость',['realestate','logistics','b2b']],
    ['apartment-management','Управление апартаментами',['realestate','travel','facility']],
    ['hoa-management','Управление жилыми домами',['realestate','facility','local']],
    ['technical-customer','Технический заказчик в строительстве',['construction','consulting','b2b']],
    ['general-contractor','Генеральный подрядчик',['construction','industrial','b2b']],
    ['fit-out','Fit-out и отделка коммерческих помещений',['construction','realestate','b2b']],
    ['modular-construction','Модульное строительство',['construction','manufacturing']],
    ['prefab-house','Производство каркасных и модульных домов',['construction','manufacturing']],
    ['foundation-company','Фундаментные работы',['construction','local']],
    ['flooring-company','Напольные покрытия и монтаж',['construction','retail','local']],
    ['ceiling-company','Натяжные потолки',['construction','local']],
    ['kitchen-company','Кухни на заказ',['manufacturing','retail','local']],
    ['wardrobe-company','Шкафы и системы хранения',['manufacturing','retail','local']],
    ['signage-company','Наружная реклама и вывески',['advertising','manufacturing','construction']],
    ['outdoor-advertising','Оператор наружной рекламы',['advertising','b2b']],
    ['media-agency','Медиаагентство',['advertising','media','b2b']],
    ['performance-agency','Performance-агентство',['advertising','it','b2b']],
    ['seo-agency','SEO-агентство',['advertising','it','b2b']],
    ['context-agency','Агентство контекстной рекламы',['advertising','it','b2b']],
    ['reputation-agency','Агентство управления репутацией',['advertising','b2b']],
    ['market-research','Маркетинговые исследования',['advertising','consulting','b2b']],
    ['product-studio','Продуктовая IT-студия',['it','design','b2b']],
    ['qa-company','Компания по тестированию ПО',['it','b2b']],
    ['devops-company','DevOps-компания',['it','b2b']],
    ['noc-provider','Сетевой операционный центр',['it','telecom','b2b']],
    ['soc-provider','SOC и мониторинг кибербезопасности',['it','security','b2b']],
    ['data-center','Дата-центр',['it','telecom','facility','b2b']],
    ['domain-hosting','Домены и хостинг',['it','telecom']],
    ['ip-telephony','IP-телефония',['it','telecom','sales']],
    ['edm-provider','Электронный документооборот',['it','finance','b2b']],
    ['payment-integrator','Платёжный интегратор',['it','finance','ecommerce']],
    ['fintech','FinTech-сервис',['it','finance']],
    ['factoring-company','Факторинговая компания',['finance','b2b']],
    ['microfinance-b2b','Финансирование малого бизнеса',['finance','b2b']],
    ['investment-advisor','Инвестиционный консультант',['finance','consulting']],
    ['business-planning','Бизнес-планирование',['consulting','finance','b2b']],
    ['strategy-consulting','Стратегический консалтинг',['consulting','b2b']],
    ['operational-consulting','Операционный консалтинг',['consulting','b2b']],
    ['quality-consulting','Системы менеджмента качества',['consulting','certification','industrial']],
    ['iso-consulting','Подготовка к ISO-сертификации',['consulting','certification','industrial']],
    ['bankruptcy-law','Юристы по банкротству',['legal','finance']],
    ['corporate-law','Корпоративные юристы',['legal','b2b']],
    ['tax-law','Налоговые юристы',['legal','finance','b2b']],
    ['labor-law','Трудовые юристы',['legal','hr','b2b']],
    ['ip-law','Юристы по интеллектуальной собственности',['legal','it','advertising']],
    ['debt-collection','Взыскание задолженности',['legal','finance','b2b']],
    ['procurement-law','Юристы по закупкам и торгам',['legal','procurement','b2b']],
    ['immigration-law','Миграционное сопровождение бизнеса',['legal','hr','b2b']],
    ['executive-search','Executive search',['hr','b2b']],
    ['mass-recruitment','Массовый подбор персонала',['hr','b2b']],
    ['temporary-staff','Временный персонал и аутстаффинг',['hr','b2b']],
    ['outsourcing-personnel','Аутсорсинг линейного персонала',['hr','b2b']],
    ['corporate-university','Корпоративный университет',['education','hr','b2b']],
    ['business-school','Бизнес-школа',['education','consulting']],
    ['driving-training','Центр обучения водителей и спецтехнике',['education','auto','industrial']],
    ['vocational-center','Центр профессионального обучения',['education','industrial','b2b']],
    ['safety-training','Учебный центр по охране труда',['education','hr','certification']],
    ['warehouse-automation','Автоматизация склада',['logistics','it','industrial']],
    ['wms-integrator','WMS-интегратор',['logistics','it','industrial']],
    ['tms-integrator','TMS-интегратор',['logistics','it','industrial']],
    ['3pl-provider','3PL-оператор',['logistics','b2b']],
    ['4pl-provider','4PL-оператор',['logistics','consulting','b2b']],
    ['parcel-locker','Постаматы и пункты выдачи',['logistics','ecommerce','retail']],
    ['pickup-point','Пункт выдачи заказов',['logistics','ecommerce','local']],
    ['ecommerce-agency','Агентство электронной коммерции',['ecommerce','advertising','it']],
    ['d2c-brand','D2C-бренд',['ecommerce','manufacturing','retail']],
    ['subscription-commerce','Подписочный интернет-магазин',['ecommerce','retail']],
    ['b2b-marketplace','B2B-маркетплейс',['ecommerce','b2b','it']],
    ['fmcg-distributor','Дистрибьютор FMCG',['supply','retail','food','b2b']],
    ['building-distributor','Дистрибьютор стройматериалов',['supply','construction','b2b']],
    ['electronics-distributor','Дистрибьютор электроники',['supply','electronics','b2b']],
    ['industrial-distributor','Промышленный дистрибьютор',['supply','industrial','b2b']],
    ['packaging-company','Упаковочная компания',['manufacturing','supply','b2b']],
    ['label-production','Производство этикеток',['manufacturing','printing','b2b']],
    ['corrugated-packaging','Гофроупаковка',['manufacturing','supply','b2b']],
    ['printing-labels','Печать этикеток и наклеек',['printing','manufacturing','b2b']],
    ['cnc-production','ЧПУ-производство',['manufacturing','industrial']],
    ['laser-cutting','Лазерная резка металла',['manufacturing','industrial']],
    ['powder-coating','Порошковая окраска',['manufacturing','industrial']],
    ['welding-production','Сварочное производство',['manufacturing','industrial']],
    ['rubber-production','Резинотехнические изделия',['manufacturing','industrial']],
    ['cable-production','Кабельная продукция',['manufacturing','energy','industrial']],
    ['pump-production','Насосное оборудование',['manufacturing','industrial']],
    ['ventilation-production','Производство вентиляционного оборудования',['manufacturing','construction','industrial']],
    ['water-equipment','Водоподготовительное оборудование',['manufacturing','facility','industrial']],
    ['industrial-repair','Промышленный ремонт и сервис',['industrial','manufacturing','b2b']],
    ['ndt-lab','Лаборатория неразрушающего контроля',['industrial','certification','b2b']],
    ['metrology','Метрологическая служба',['industrial','certification','b2b']],
    ['lab-testing','Испытательная лаборатория',['certification','industrial','b2b']],
    ['food-certification','Сертификация пищевой продукции',['certification','food','b2b']],
    ['medical-certification','Регистрация и сертификация медизделий',['certification','medical','b2b']],
    ['customs-certification','Сертификация для импорта и ВЭД',['certification','supply','b2b']],
    ['office-cleaning','Клининг офисов',['cleaning','facility','b2b']],
    ['industrial-cleaning','Промышленный клининг',['cleaning','industrial','b2b']],
    ['window-cleaning','Мойка фасадов и окон',['cleaning','facility']],
    ['laundry-b2b','Прачечная для гостиниц и ресторанов',['cleaning','horeca','b2b']],
    ['pest-control','Пест-контроль для бизнеса',['cleaning','food','horeca','b2b']],
    ['facility-management','Facility management',['facility','realestate','b2b']],
    ['maintenance-company','Техническое обслуживание зданий',['facility','construction','b2b']],
    ['generator-service','Обслуживание генераторов',['facility','energy','industrial']],
    ['boiler-service','Обслуживание котельных',['facility','energy','industrial']],
    ['fire-safety-service','Пожарная безопасность и обслуживание систем',['security','facility','b2b']],
    ['access-control','СКУД и контроль доступа',['security','it','facility']],
    ['alarm-monitoring','Пультовая охрана',['security','local','b2b']],
    ['private-security','Частная охранная организация',['security','b2b']],
    ['event-security','Охрана мероприятий',['security','events']],
    ['photo-production','Коммерческая фотосъёмка',['media','advertising','b2b']],
    ['animation-studio','Анимационная студия',['media','design','advertising']],
    ['motion-design','Motion design студия',['media','design','advertising']],
    ['sound-studio','Студия звукозаписи',['media','local']],
    ['voiceover-studio','Студия озвучивания',['media','advertising']],
    ['streaming-studio','Студия онлайн-трансляций',['media','events','b2b']],
    ['merch-production','Производство мерча',['manufacturing','advertising','b2b']],
    ['corporate-gifts','Корпоративные подарки',['retail','advertising','b2b']],
    ['promo-staff','Промоперсонал',['advertising','hr','events']],
    ['event-equipment','Прокат оборудования для мероприятий',['events','rent']],
    ['decor-studio','Декор и оформление мероприятий',['events','design','local']],
    ['ticketing-service','Билетный сервис',['events','it']],
    ['conference-platform','Платформа для конференций',['events','it','b2b']],
    ['green-energy','Возобновляемая энергетика',['energy','industrial']],
    ['energy-efficiency','Энергоэффективность зданий',['energy','facility','consulting']],
    ['industrial-energy','Энергоснабжение предприятий',['energy','industrial','b2b']],
    ['water-utility-service','Инженерные системы водоснабжения',['facility','construction','industrial']],
    ['environmental-consulting','Экологический консалтинг',['ecology','consulting','industrial']],
    ['waste-recycling-plant','Переработка вторсырья',['ecology','manufacturing','industrial']],
    ['hazardous-waste-service','Обращение с промышленными отходами',['ecology','industrial','b2b']],
    ['farm-equipment-service','Сервис сельхозтехники',['agro','industrial','local']],
    ['irrigation-company','Системы полива и орошения',['agro','construction','industrial']],
    ['agro-consulting','Агроконсалтинг',['agro','consulting']],
    ['seed-company','Семенная компания',['agro','supply']],
    ['animal-feed','Корма для животных',['agro','manufacturing','supply']],
    ['veterinary-lab','Ветеринарная лаборатория',['pets','medical','b2b']],
    ['pet-hotel','Гостиница для животных',['pets','local']],
    ['dog-training','Кинологический центр',['pets','education','local']],
    ['pet-food-production','Производство кормов для животных',['pets','manufacturing','food']],
    ['funeral-agency','Ритуальное агентство',['local','service']],
    ['storage-service','Камеры хранения и хранение вещей',['rent','local']],
    ['self-storage','Self-storage склад',['rent','realestate','local']],
    ['laundromat','Прачечная самообслуживания',['cleaning','local']],
    ['dry-cleaning','Химчистка',['cleaning','local']],
    ['watch-repair','Ремонт часов',['local','electronics']],
    ['jewelry-repair','Ювелирная мастерская',['local','manufacturing']],
    ['key-service','Изготовление ключей',['local','manufacturing']],
    ['engraving-service','Гравировка',['local','manufacturing']],
    ['photo-print','Фотопечать',['printing','local']],
    ['document-center','Центр печати и документов',['printing','local']]
  ].map(function (x) { return { slug:x[0], name:x[1], tags:x[2] }; });

  const services = [
    ['medical-seo','SEO для медицинской клиники','service',['medical','advertising']],
    ['medical-context','Контекстная реклама медицинских услуг','service',['medical','advertising']],
    ['clinic-crm','Внедрение CRM в клинике','service',['medical','it']],
    ['clinic-callcenter','Обработка обращений пациентов','service',['medical','sales']],
    ['clinic-reputation','Работа с репутацией клиники','service',['medical','advertising']],
    ['clinic-website','Разработка сайта клиники','service',['medical','it']],
    ['medical-equipment-maintenance','Техническое обслуживание медоборудования','work',['medical','industrial']],
    ['medical-equipment-supply','Поставка медицинского оборудования','supply',['medical','industrial']],
    ['dental-equipment-maintenance','Обслуживание стоматологического оборудования','work',['medical','industrial']],
    ['beauty-leads','Лидогенерация для салона красоты','service',['beauty','advertising']],
    ['beauty-crm','CRM и онлайн-запись для салона','service',['beauty','it']],
    ['fitness-leads','Лидогенерация для фитнес-клуба','service',['fitness','advertising']],
    ['fitness-crm','Автоматизация фитнес-клуба','service',['fitness','it']],
    ['restaurant-crm','CRM и автоматизация ресторана','service',['horeca','it']],
    ['restaurant-delivery','Запуск собственной доставки ресторана','service',['horeca','logistics','it']],
    ['restaurant-procurement','Организация закупок для ресторана','service',['horeca','procurement','food']],
    ['hotel-automation','Автоматизация гостиницы','service',['horeca','travel','it']],
    ['hotel-marketing','Продвижение гостиницы','service',['horeca','travel','advertising']],
    ['hotel-management-service','Управление гостиничным объектом','service',['horeca','travel','facility']],
    ['tour-leads','Лидогенерация туристических услуг','service',['travel','advertising']],
    ['tour-website','Разработка сайта туроператора','service',['travel','it']],
    ['transfer-service','Трансфер пассажиров','service',['travel','logistics','auto']],
    ['fleet-service','Комплексное обслуживание автопарка','service',['auto','logistics','b2b']],
    ['truck-maintenance','Техническое обслуживание грузовиков','work',['auto','industrial']],
    ['commercial-auto-repair','Ремонт коммерческого транспорта','work',['auto','industrial']],
    ['car-rental-service','Аренда автомобиля','rent',['auto','travel']],
    ['truck-rental-service','Аренда грузового автомобиля','rent',['auto','logistics']],
    ['special-equipment-rental-service','Аренда спецтехники','rent',['construction','industrial']],
    ['tool-rental-service','Аренда строительного инструмента','rent',['construction','local']],
    ['real-estate-ads','Продвижение объектов недвижимости','service',['realestate','advertising']],
    ['real-estate-photo','Фотосъёмка объекта недвижимости','service',['realestate','media']],
    ['real-estate-video','Видеосъёмка объекта недвижимости','service',['realestate','media']],
    ['real-estate-appraisal','Оценка недвижимости','service',['realestate','finance']],
    ['rental-management','Управление арендой объекта','service',['realestate','facility']],
    ['commercial-property-management','Управление коммерческой недвижимостью','service',['realestate','facility','b2b']],
    ['technical-customer-service','Функции технического заказчика','service',['construction','consulting']],
    ['general-contracting','Генеральный подряд','work',['construction','industrial']],
    ['fitout-service','Отделка коммерческих помещений','work',['construction','realestate']],
    ['foundation-work','Фундаментные работы','work',['construction']],
    ['flooring-install','Монтаж напольных покрытий','work',['construction']],
    ['ceiling-install','Монтаж потолков','work',['construction']],
    ['signage-production','Изготовление и монтаж вывесок','work',['advertising','manufacturing','construction']],
    ['outdoor-placement','Размещение наружной рекламы','service',['advertising']],
    ['performance-marketing','Performance-маркетинг','service',['advertising','it']],
    ['reputation-management','Управление репутацией бренда','service',['advertising']],
    ['market-research-service','Маркетинговое исследование','service',['advertising','consulting']],
    ['product-development','Разработка цифрового продукта','service',['it','design']],
    ['qa-outsourcing','Аутсорсинг тестирования ПО','service',['it']],
    ['devops-outsourcing','DevOps-аутсорсинг','service',['it']],
    ['soc-service','SOC-мониторинг и реагирование','service',['it','security']],
    ['data-center-rent','Аренда серверной инфраструктуры','rent',['it','telecom']],
    ['ip-telephony-service','Внедрение IP-телефонии','service',['it','telecom','sales']],
    ['edm-integration','Внедрение электронного документооборота','service',['it','finance']],
    ['payment-integration','Интеграция онлайн-платежей','service',['it','finance','ecommerce']],
    ['factoring-service','Факторинговое финансирование','service',['finance','b2b']],
    ['financial-model','Разработка финансовой модели','service',['finance','consulting']],
    ['business-plan','Разработка бизнес-плана','service',['finance','consulting']],
    ['strategy-session','Стратегическая сессия','service',['consulting','b2b']],
    ['process-optimization','Оптимизация бизнес-процессов','service',['consulting','b2b']],
    ['iso-preparation','Подготовка к сертификации ISO','service',['certification','consulting','industrial']],
    ['quality-system','Внедрение системы менеджмента качества','service',['certification','consulting','industrial']],
    ['bankruptcy-support','Сопровождение банкротства','service',['legal','finance']],
    ['corporate-law-service','Корпоративное юридическое сопровождение','service',['legal','b2b']],
    ['tax-law-service','Налоговое юридическое сопровождение','service',['legal','finance']],
    ['labor-law-service','Трудовое юридическое сопровождение','service',['legal','hr']],
    ['ip-law-service','Защита интеллектуальной собственности','service',['legal','it','advertising']],
    ['debt-collection-service','Взыскание дебиторской задолженности','service',['legal','finance']],
    ['tender-law','Юридическое сопровождение закупок','service',['legal','procurement']],
    ['migration-support','Миграционное сопровождение сотрудников','service',['legal','hr']],
    ['executive-search-service','Поиск руководителей и редких специалистов','service',['hr']],
    ['mass-recruitment-service','Массовый подбор персонала','service',['hr']],
    ['temporary-staff-service','Предоставление временного персонала','service',['hr']],
    ['personnel-outsourcing','Аутсорсинг линейного персонала','service',['hr']],
    ['training-program','Разработка программы обучения','service',['education','hr']],
    ['industrial-training','Профессиональное обучение сотрудников','service',['education','industrial']],
    ['safety-training-service','Обучение охране труда','service',['education','hr','certification']],
    ['warehouse-automation-service','Автоматизация складских процессов','service',['logistics','it']],
    ['wms','Внедрение WMS','service',['logistics','it']],
    ['tms','Внедрение TMS','service',['logistics','it']],
    ['third-party-logistics','3PL-обслуживание','service',['logistics','b2b']],
    ['fourth-party-logistics','4PL-управление логистикой','service',['logistics','consulting']],
    ['pickup-operations','Организация пункта выдачи заказов','service',['logistics','ecommerce']],
    ['ecommerce-strategy','Стратегия электронной коммерции','service',['ecommerce','consulting']],
    ['d2c-launch','Запуск D2C-продаж','service',['ecommerce','retail']],
    ['b2b-marketplace-dev','Разработка B2B-маркетплейса','service',['ecommerce','it','b2b']],
    ['distribution-service','Дистрибуция товаров','service',['supply','retail','b2b']],
    ['fmcg-supply','Поставка FMCG-товаров','supply',['supply','retail','food']],
    ['construction-supply','Поставка строительных материалов','supply',['supply','construction']],
    ['industrial-distribution','Поставка промышленной продукции','supply',['supply','industrial']],
    ['packaging-production-service','Производство упаковки под заказ','work',['manufacturing','supply']],
    ['label-printing','Печать этикеток и наклеек','work',['printing','manufacturing']],
    ['cnc-machining','Механообработка на ЧПУ','work',['manufacturing','industrial']],
    ['laser-cutting-service','Лазерная резка металла','work',['manufacturing','industrial']],
    ['powder-coating-service','Порошковая окраска','work',['manufacturing','industrial']],
    ['welding-service','Сварочные работы','work',['manufacturing','industrial']],
    ['industrial-maintenance','Промышленное техобслуживание','work',['industrial','manufacturing']],
    ['ndt-service','Неразрушающий контроль','service',['industrial','certification']],
    ['metrology-service','Метрологическая поверка и калибровка','service',['industrial','certification']],
    ['laboratory-testing','Лабораторные испытания продукции','service',['certification','industrial']],
    ['food-certification-service','Сертификация пищевой продукции','service',['certification','food']],
    ['medical-registration','Регистрация медицинских изделий','service',['certification','medical']],
    ['import-certification','Сертификация импортной продукции','service',['certification','supply']],
    ['office-cleaning-service','Регулярный клининг офиса','service',['cleaning','facility']],
    ['industrial-cleaning-service','Промышленный клининг','service',['cleaning','industrial']],
    ['facade-cleaning','Мойка фасада','service',['cleaning','facility']],
    ['hotel-laundry','Прачечное обслуживание гостиницы','service',['cleaning','horeca']],
    ['restaurant-laundry','Прачечное обслуживание ресторана','service',['cleaning','horeca']],
    ['pest-control-service','Пест-контроль и дезинсекция','service',['cleaning','food','horeca']],
    ['facility-management-service','Комплексное управление объектом','service',['facility','realestate']],
    ['building-maintenance','Техническое обслуживание здания','service',['facility','construction']],
    ['generator-maintenance','Сервис генераторных установок','work',['energy','facility']],
    ['boiler-maintenance','Обслуживание котельной','work',['energy','facility']],
    ['fire-system-maintenance','Обслуживание пожарных систем','work',['security','facility']],
    ['access-control-install','Монтаж системы контроля доступа','work',['security','it','facility']],
    ['security-monitoring','Пультовая охрана объекта','service',['security','facility']],
    ['physical-security','Физическая охрана объекта','service',['security','b2b']],
    ['event-security-service','Охрана мероприятия','service',['security','events']],
    ['commercial-photo','Коммерческая фотосъёмка','service',['media','advertising']],
    ['animation-production','Производство анимационного ролика','service',['media','design']],
    ['motion-design-service','Motion-дизайн','service',['media','design']],
    ['voiceover','Озвучивание роликов и рекламы','service',['media','advertising']],
    ['livestream','Организация онлайн-трансляции','service',['media','events']],
    ['merch-production-service','Производство брендированного мерча','work',['manufacturing','advertising']],
    ['corporate-gifts-supply','Поставка корпоративных подарков','supply',['retail','advertising','b2b']],
    ['promo-staff-service','Промоперсонал на мероприятие','service',['advertising','hr','events']],
    ['event-equipment-rental','Аренда оборудования для мероприятия','rent',['events']],
    ['event-decoration','Оформление мероприятия','work',['events','design']],
    ['ticketing-integration','Подключение билетного сервиса','service',['events','it']],
    ['conference-platform-service','Платформа для онлайн-конференции','service',['events','it']],
    ['energy-efficiency-audit','Аудит энергоэффективности','service',['energy','consulting']],
    ['industrial-energy-service','Энергосервис промышленного объекта','service',['energy','industrial']],
    ['water-system-service','Монтаж и обслуживание водоснабжения','work',['facility','construction']],
    ['environmental-reporting','Экологическая отчётность','service',['ecology','consulting']],
    ['recycling-service-b2b','Переработка вторсырья для бизнеса','service',['ecology','industrial']],
    ['industrial-waste-service','Вывоз и утилизация промышленных отходов','service',['ecology','industrial']],
    ['farm-machinery-repair','Ремонт сельхозтехники','work',['agro','industrial']],
    ['irrigation-install','Монтаж систем полива','work',['agro','construction']],
    ['agro-consulting-service','Агрономический консалтинг','service',['agro','consulting']],
    ['seed-supply','Поставка семян','supply',['agro']],
    ['feed-supply','Поставка кормов','supply',['agro','pets']],
    ['vet-lab-service','Ветеринарные лабораторные исследования','service',['pets','medical']],
    ['pet-hotel-service','Передержка животных','service',['pets','local']],
    ['dog-training-service','Дрессировка собак','service',['pets','education']],
    ['self-storage-rent','Аренда складского бокса','rent',['rent','realestate']],
    ['dry-cleaning-service','Химчистка изделий','service',['cleaning','local']],
    ['watch-repair-service','Ремонт часов','work',['local','electronics']],
    ['jewelry-repair-service','Ремонт ювелирных изделий','work',['local','manufacturing']],
    ['engraving','Гравировка изделий','work',['local','manufacturing']],
    ['photo-print-service','Фотопечать','work',['printing','local']],
    ['document-printing','Печать и копирование документов','work',['printing','local']]
  ].map(function (x) { return { slug:x[0], name:x[1], mode:x[2], tags:x[3] }; });

  appendUnique(RK.niches, niches);
  appendUnique(RK.services, services);
})();
